### ISSUE TITLE
Design website sitemap

### ISSUE THREAD

**Issue by syberphunk** [UKHackspaces/UKHackspaces.github.io#6]

**Comment by syberphunk** [comment]
Introduction to:
- Who we are
- What we're trying to Achieve
- Where we're at right now
  How to Join in
- Foundation's definition of a Hackspace
  Glossary of Terms and Acronyms
  Current Member Spaces
- Map of Current Member Spaces

**Comment by idnorton** [comment]
Based on the current site iterations @syberphunk is this still pending do you think or have we got enough there that this is mostly done now?

**Comment by Axford** [comment]
I'd call this done, as future work is covered by other tasks
